#!/bin/bash
##--------------------------------------------------------------------
## Copyright (c) 2018 Dianomic Systems
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##--------------------------------------------------------------------
##
## Author: Ashish Jabble
##

set -e

yes Y |  sudo apt-get update
yes Y |  sudo apt-get upgrade

yes Y |  sudo apt-get install curl

yes Y |  sudo apt-get install cmake g++ make build-essential autoconf automake
yes Y |  sudo apt-get install libtool libboost-dev libboost-system-dev libboost-thread-dev libpq-dev libssl-dev
yes Y |  sudo apt-get install python-setuptools python3-dbus python3-dev python3-pip

yes Y |  sudo apt-get install uuid-dev

yes Y |  sudo apt-get install sqlite3 libsqlite3-dev

yes Y | sudo apt-get install nginx-light

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
yes Y | sudo apt-get install -y nodejs
yes Y | sudo npm install -g yarn

#####################################################
# Clone FogLAMP, foglamp-gui, foglamp-south-sinusoid
####################################################

GIT_ROOT=`pwd`
git clone -b develop --single-branch https://github.com/foglamp/FogLAMP.git
git clone -b develop --single-branch https://github.com/foglamp/foglamp-gui.git
git clone https://github.com/foglamp/foglamp-south-sinusoid.git

# FogLAMP install
cd ${GIT_ROOT}/FogLAMP
sudo make install
cd ..

# Prepare foglamp-gui build artifacts
cd ${GIT_ROOT}/foglamp-gui
rm -rf dist
./build.sh
cd ..
